/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controlles.PasajeroController;
import com.mycompany.hotel.models.Pasajero;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mi pc
 */
public class ABMPasajero extends javax.swing.JFrame {

    private PasajeroController pasajeroController;
    private Pasajero pasajeroObj;
    private List<Pasajero> pasajeros;

    public ABMPasajero() {
        pasajeroController = new PasajeroController();
        initComponents();
        this.refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistroCliente = new javax.swing.JPanel();
        lblTituloRegistroCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreoelectronico = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        PanelListadoPasajeros = new javax.swing.JPanel();
        lblTituloListadoDePasajeros = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPasajeros = new javax.swing.JTable();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloRegistroCliente.setText("Registro Pasajero");

        lblNombre.setText("Nombre:");

        txtNombre.addActionListener(formListener);

        lblApellido.setText("Apellido:");

        lblTelefono.setText("Telefono:");

        txtDni.addActionListener(formListener);

        lblDni.setText("Dni:");

        lblCorreo.setText("Correo electronico:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(formListener);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(formListener);

        javax.swing.GroupLayout PanelRegistroClienteLayout = new javax.swing.GroupLayout(PanelRegistroCliente);
        PanelRegistroCliente.setLayout(PanelRegistroClienteLayout);
        PanelRegistroClienteLayout.setHorizontalGroup(
            PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblTituloRegistroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblId))
                    .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addComponent(lblCorreo))
                                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCorreoelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnCancelar))))
                            .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDni)
                                    .addComponent(lblApellido)
                                    .addComponent(lblNombre))
                                .addGap(42, 42, 42)
                                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRegistroClienteLayout.setVerticalGroup(
            PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroClienteLayout.createSequentialGroup()
                        .addComponent(lblTituloRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroClienteLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(18, 18, 18)))
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addGap(50, 50, 50)
                .addGroup(PanelRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        lblTituloListadoDePasajeros.setText("Listado de pasajeros");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(formListener);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(formListener);

        tablaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dni", "Telefono", "Correo electronico"
            }
        ));
        jScrollPane2.setViewportView(tablaPasajeros);

        javax.swing.GroupLayout PanelListadoPasajerosLayout = new javax.swing.GroupLayout(PanelListadoPasajeros);
        PanelListadoPasajeros.setLayout(PanelListadoPasajerosLayout);
        PanelListadoPasajerosLayout.setHorizontalGroup(
            PanelListadoPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoPasajerosLayout.createSequentialGroup()
                .addGroup(PanelListadoPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListadoPasajerosLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnEditar)
                        .addGap(82, 82, 82)
                        .addComponent(btnBorrar))
                    .addGroup(PanelListadoPasajerosLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTituloListadoDePasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelListadoPasajerosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelListadoPasajerosLayout.setVerticalGroup(
            PanelListadoPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoPasajerosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloListadoDePasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelListadoPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListadoPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelListadoPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(PanelRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == txtNombre) {
                ABMPasajero.this.txtNombreActionPerformed(evt);
            }
            else if (evt.getSource() == txtDni) {
                ABMPasajero.this.txtDniActionPerformed(evt);
            }
            else if (evt.getSource() == btnGuardar) {
                ABMPasajero.this.btnGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == btnEditar) {
                ABMPasajero.this.btnEditarActionPerformed(evt);
            }
            else if (evt.getSource() == btnBorrar) {
                ABMPasajero.this.btnBorrarActionPerformed(evt);
            }
            else if (evt.getSource() == btnCancelar) {
                ABMPasajero.this.btnCancelarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int filanum = tablaPasajeros.getSelectedRow();
        if (filanum < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        } else {
            try {
                DefaultTableModel modelo = (DefaultTableModel) tablaPasajeros.getModel();
                int id = (int) modelo.getValueAt(filanum, 0);
                pasajeroObj = pasajeroController.recuperarPorId(id);
                lblId.setText(String.valueOf(pasajeroObj.getId()));
                txtNombre.setText(pasajeroObj.getNombre());
                txtApellido.setText(pasajeroObj.getApellido());
                txtDni.setText(String.valueOf(pasajeroObj.getDNI()));
                txtTelefono.setText(String.valueOf(pasajeroObj.getTelefono()));
                txtCorreoelectronico.setText(pasajeroObj.getEmail());

            } catch (SQLException ex) {
                Logger.getLogger(ABMPasajero.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.Agregar();
        this.LimpiarCampos();
        this.refrescar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = tablaPasajeros.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");

        } else {
            DefaultTableModel model = (DefaultTableModel) tablaPasajeros.getModel();
            int id = (int) model.getValueAt(fila, 0);
            int opc = JOptionPane.showConfirmDialog(null, "Estas Seguro?");
            if (opc == 0) {
                try {
                    pasajeroController.borrar(id);

                } catch (SQLException ex) {
                    Logger.getLogger(ABMPasajero.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.refrescar();
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.LimpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMPasajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelListadoPasajeros;
    private javax.swing.JPanel PanelRegistroCliente;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloListadoDePasajeros;
    private javax.swing.JLabel lblTituloRegistroCliente;
    private javax.swing.JTable tablaPasajeros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreoelectronico;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void refrescar() {
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Apellido");
            dtm.addColumn("DNI");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            pasajeros = pasajeroController.recuperarTodos();
            Object[] fila = new Object[6];
            for (int i = 0; i < pasajeros.size(); i++) {
                pasajeroObj = pasajeros.get(i);
                fila[0] = pasajeroObj.getId();
                fila[1] = pasajeroObj.getNombre();
                fila[2] = pasajeroObj.getApellido();
                fila[3] = pasajeroObj.getDNI();
                fila[4] = pasajeroObj.getTelefono();
                fila[5] = pasajeroObj.getEmail();
                dtm.addRow(fila);
            }
            tablaPasajeros.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ABMPasajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Agregar() {
        try {
            Integer id;
            id = null;
            if (lblId.getText() != null && lblId.getText() != "") {
                id = Integer.parseInt(lblId.getText());
            }
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            int dni = Integer.parseInt(txtDni.getText());
            int telefono = Integer.parseInt(txtTelefono.getText());
            String correo = txtCorreoelectronico.getText();
        
            if (id == null) {
                try {
                    pasajeroController.crear(nombre,apellido,dni,telefono,correo);
                } catch (SQLException ex) {
                    Logger.getLogger(ABMPasajero.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "El pasajero se guardo con exito");
            } else {
                pasajeroController.actualizar(id,nombre,apellido,dni,telefono,correo);
                JOptionPane.showMessageDialog(null, "El pasajero se actualizo correctamente");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El dni y telefono deben ser numericos");
        }
    }

    public void LimpiarCampos() {
        lblId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtCorreoelectronico.setText("");
    }
}
