/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controller.HabitacionController;
import com.mycompany.hotel.dto.HabitacionDTO;
import com.toedter.calendar.JCalendar;

import javax.swing.*;
import java.sql.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mauro
 */
public class BuscarHabitacionesPorRangoDeFechas extends javax.swing.JPanel {

     private HabitacionController habitacionController;
    private JCalendar FechaCheckin;
    private JCalendar FechaCheckout;
    private JComboBox<Integer> CboxCantidadPersonas;
    private JButton btnBuscar;
    private JComboBox<HabitacionDTO> CboxHabitaciones;

    /**
     * Creates new form BuscarHabitacionEnRangoDeFechas
     */
    public BuscarHabitacionesPorRangoDeFechas() {
        habitacionController = new HabitacionController();
        initComponents();
    }

    public void buscarHabitacionesPorFecha() {
        try {
            java.util.Date checkinUtil = FechaCheckin.getDate();
            java.util.Date checkoutUtil = FechaCheckout.getDate();

            if (checkinUtil == null || checkoutUtil == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas.");
                return;
            }

            if (!checkoutUtil.after(checkinUtil)) {
                JOptionPane.showMessageDialog(this, "La fecha de checkout debe ser posterior a la de checkin.");
                return;
            }

            Date checkin = new Date(checkinUtil.getTime());
            Date checkout = new Date(checkoutUtil.getTime());

            Integer cantidad = (Integer) CboxCantidadPersonas.getSelectedItem();

            if (cantidad == null || cantidad < 1 & cantidad > 4) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar la cantidad de personas.");
                return;
            }

            List<HabitacionDTO> habitaciones = habitacionController.buscarDisponibles(checkin, checkout, cantidad);

            CboxHabitaciones.removeAllItems();

            if (habitaciones == null || habitaciones.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron habitaciones disponibles.");
                return;
            }

            for (HabitacionDTO h : habitaciones) {
                CboxHabitaciones.addItem(h);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar habitaciones: " + ex.getMessage());
            Logger.getLogger(BuscarHabitacionesPorRangoDeFechas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendarCheckin = new com.toedter.calendar.JCalendar();
        jCalendarCheckout = new com.toedter.calendar.JCalendar();
        CBoxCantidadDePersonas = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        CBoxHabitaciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        CBoxCantidadDePersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBoxCantidadDePersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCantidadDePersonasActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        CBoxHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBoxHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxHabitacionesActionPerformed(evt);
            }
        });

        jLabel1.setText("    Checkin");

        jLabel2.setText(" Checkout");

        jLabel3.setText("Cantidad de Personas");

        jLabel4.setText("     Habitaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(CBoxCantidadDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jCalendarCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButtonBuscar)
                                .addGap(105, 105, 105)
                                .addComponent(CBoxHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jCalendarCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendarCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendarCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBoxCantidadDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscar)
                            .addComponent(CBoxHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarHabitacionesPorFecha();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void CBoxCantidadDePersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCantidadDePersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxCantidadDePersonasActionPerformed

    private void CBoxHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxHabitacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxCantidadDePersonas;
    private javax.swing.JComboBox<String> CBoxHabitaciones;
    private javax.swing.JButton jButtonBuscar;
    private com.toedter.calendar.JCalendar jCalendarCheckin;
    private com.toedter.calendar.JCalendar jCalendarCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
