/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controller.HabitacionController;
import com.mycompany.hotel.controller.PasajeroController;
import com.mycompany.hotel.controller.ReservaController;
import com.mycompany.hotel.dto.HabitacionDTO;
import com.mycompany.hotel.dto.PasajeroDTO;
import com.mycompany.hotel.dto.ReservaDTO;
import com.mycompany.hotel.view.NuevaReserva;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mi pc
 */
public class ListaReservas extends javax.swing.JPanel {

    /**
     * Creates new form ListaReservas
     */
    private ReservaController reservaController;
    private PasajeroController pasajeroController;
    private HabitacionController habitacionController;
    private ReservaDTO reservaDTO;
    private PasajeroDTO pasajeroDTO;
    private HabitacionDTO habitacionDTO;

    public ListaReservas() {
        this.reservaController = new ReservaController();
        this.pasajeroController = new PasajeroController();
        this.habitacionController = new HabitacionController();
        this.pasajeroDTO = new PasajeroDTO();
        this.habitacionDTO = new HabitacionDTO();
        initComponents();
        refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReservas = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        CboxBuscar = new javax.swing.JComboBox<>();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Reservas"));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtBuscar.addActionListener(formListener);
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 52, 232, -1));

        BtnBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(formListener);
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 52, -1, -1));

        TablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Habitacion", "Checkin", "Checkout", "Seña", "Pasajero"
            }
        ));
        jScrollPane1.setViewportView(TablaReservas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 101, 1178, -1));

        BtnEditar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(formListener);
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 544, 159, -1));

        BtnBorrar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(formListener);
        add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 544, 160, -1));

        CboxBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CboxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "#", "Fecha", "Checkin", "Checkout", "Habitacion", "Seña", "Pasajero" }));
        CboxBuscar.addActionListener(formListener);
        add(CboxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 52, 169, -1));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == TxtBuscar) {
                ListaReservas.this.TxtBuscarActionPerformed(evt);
            }
            else if (evt.getSource() == BtnBuscar) {
                ListaReservas.this.BtnBuscarActionPerformed(evt);
            }
            else if (evt.getSource() == BtnEditar) {
                ListaReservas.this.BtnEditarActionPerformed(evt);
            }
            else if (evt.getSource() == BtnBorrar) {
                ListaReservas.this.BtnBorrarActionPerformed(evt);
            }
            else if (evt.getSource() == CboxBuscar) {
                ListaReservas.this.CboxBuscarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    public void refrescar() {

        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("N° Habitación");  // visible para el usuario
            dtm.addColumn("Checkin");
            dtm.addColumn("Checkout");
            dtm.addColumn("Seña");
            dtm.addColumn("Pasajero");       // visible
            dtm.addColumn("ID_habitacion");  // oculta
            dtm.addColumn("ID_pasajero");    // oculta
            List<ReservaDTO> reservas = reservaController.recuperarTodos();

            for (ReservaDTO r : reservas) {

                String nroHabitacion = habitacionController.obtenerNumeroHabitacionPorId(r.getId_habitacion());
                String nombrePasajero = pasajeroController.obtenerNombreCompletoPorId(r.getId_pasajero());
                dtm.addRow(new Object[]{
                    r.getId(),
                    nroHabitacion,
                    r.getChekin(),
                    r.getCheckout(),
                    r.getSenia(),
                    nombrePasajero,
                    r.getId_habitacion(),
                    r.getId_pasajero()
                });
            }

            TablaReservas.setModel(dtm);
            TablaReservas.getColumnModel().getColumn(6).setMinWidth(0);
            TablaReservas.getColumnModel().getColumn(6).setMaxWidth(0);
            TablaReservas.getColumnModel().getColumn(6).setWidth(0);

            TablaReservas.getColumnModel().getColumn(7).setMinWidth(0);
            TablaReservas.getColumnModel().getColumn(7).setMaxWidth(0);
            TablaReservas.getColumnModel().getColumn(7).setWidth(0);

        } catch (SQLException ex) {
            Logger.getLogger(ListaHabitaciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void borrar() {
        int fila = TablaReservas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");

        } else {
            DefaultTableModel model = (DefaultTableModel) TablaReservas.getModel();
            int id = (int) model.getValueAt(fila, 0);
            int opc = JOptionPane.showConfirmDialog(null, "Estas Seguro?");
            if (opc == 0) {
                try {
                    reservaController.borrar(id);
                    this.refrescar();
                } catch (SQLException ex) {
                    Logger.getLogger(ListaPasajeros.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }

    public void actualizar() throws SQLException {
    int fila = TablaReservas.getSelectedRow();

    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
    } else {
        DefaultTableModel model = (DefaultTableModel) TablaReservas.getModel();

        int id = (int) model.getValueAt(fila, 0); // ID reserva
        int id_habitacion = (int) model.getValueAt(fila, 6); // ID real de la habitación
        int id_pasajero = (int) model.getValueAt(fila, 7); // ID real del pasajero

        Date checkin = (Date) model.getValueAt(fila, 2);
        Date checkout = (Date) model.getValueAt(fila, 3);
        float senia = (float) model.getValueAt(fila, 4);

        PasajeroDTO p = pasajeroController.recuperarPorId(id_pasajero);
        HabitacionDTO h = habitacionController.recuperarPorId(id_habitacion);
        int capacidad = habitacionController.calcularCapacidad(h);

        NuevaReserva panelEditar = new NuevaReserva(id, h, checkin, checkout, senia, p, capacidad);

        JDialog dialog = new JDialog();
        dialog.setTitle("Editar Reserva");
        dialog.setModal(true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.getContentPane().add(panelEditar);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

   
    }
    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        this.borrar();
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        try {
            this.actualizar();
        } catch (SQLException ex) {
            Logger.getLogger(ListaReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.refrescar();
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void CboxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JComboBox<String> CboxBuscar;
    private javax.swing.JTable TablaReservas;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
