/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class ListaPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form ListaPasajeros
     */
    public ListaPasajeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPasajeros = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CboxBuscar = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Pasajeros"));
        setToolTipText("");
        setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 39, 295, -1));

        BtnBuscar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        BtnBuscar.setText("Buscar");
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 39, -1, -1));

        TablaPasajeros.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TablaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nombre", "Apellido", "Dni", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(TablaPasajeros);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 95, 1170, 429));

        BtnEditar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        BtnEditar.setText("Editar");
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 546, 143, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButton1.setText("Borrar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 546, 143, -1));

        CboxBuscar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        CboxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "#", "Nombre", "Apellido", "Dni", "Telefono", "Correo", "" }));
        add(CboxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 39, 182, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JComboBox<String> CboxBuscar;
    private javax.swing.JTable TablaPasajeros;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
