/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class ListaReservas extends javax.swing.JPanel {

    /**
     * Creates new form ListaReservas
     */
    public ListaReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReservas = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        CboxBuscar = new javax.swing.JComboBox<>();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Reservas"));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtBuscar.addActionListener(formListener);
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 52, 232, -1));

        BtnBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(formListener);
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 52, -1, -1));

        TablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Fecha ", "Habitacion", "Checkin", "Checkout", "Seña", "Pasajero"
            }
        ));
        jScrollPane1.setViewportView(TablaReservas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 101, 1178, -1));

        BtnEditar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnEditar.setText("Editar");
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 544, 159, -1));

        BtnBorrar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnBorrar.setText("Borrar");
        add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 544, 160, -1));

        CboxBuscar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CboxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "#", "Fecha", "Checkin", "Checkout", "Habitacion", "Seña", "Pasajero" }));
        add(CboxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 52, 169, -1));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == TxtBuscar) {
                ListaReservas.this.TxtBuscarActionPerformed(evt);
            }
            else if (evt.getSource() == BtnBuscar) {
                ListaReservas.this.BtnBuscarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JComboBox<String> CboxBuscar;
    private javax.swing.JTable TablaReservas;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
