/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class ListaHabitaciones extends javax.swing.JPanel {

    /**
     * Creates new form ListaHabitaciones
     */
    public ListaHabitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new javax.swing.JTextField();
        CboxBuscar = new javax.swing.JComboBox<>();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHabitaciones = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Habitaciones"));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 42, 304, -1));

        CboxBuscar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        CboxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "#", "Numero", "Camas simple", "Camas doble", "Precio" }));
        add(CboxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 42, -1, -1));

        BtnBuscar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnBuscar.setText("Buscar");
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 42, -1, -1));

        TablaHabitaciones.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TablaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Numero", "Cama Simple", "Cama Doble", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaHabitaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 91, 1158, 442));

        BtnEditar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.setPreferredSize(new java.awt.Dimension(123, 43));
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 546, -1, -1));

        BtnBorrar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.setPreferredSize(new java.awt.Dimension(123, 43));
        add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 546, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JComboBox<String> CboxBuscar;
    private javax.swing.JTable TablaHabitaciones;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
