/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controller.PasajeroController;
import com.mycompany.hotel.dto.PasajeroDTO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mi pc
 */
public class NuevoPasajero extends javax.swing.JPanel {

    public NuevoPasajero(JTextField txtApellido, JTextField txtCorreo, JTextField txtDni, JTextField txtNombre, JTextField txtTelefono) {
        this.txtApellido = txtApellido;
        this.txtCorreo = txtCorreo;
        this.txtDni = txtDni;
        this.txtNombre = txtNombre;
        this.txtTelefono = txtTelefono;
    }

    private PasajeroController pasajeroController;
    private PasajeroDTO pasajeroDto;

    public NuevoPasajero(int id, String nombre, String apellido, String dni, String telefono, String correo) {
        this();
        LblId.setText(String.valueOf(id));
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtDni.setText(dni);
        txtTelefono.setText(telefono);
        txtCorreo.setText(correo);
    }

    public NuevoPasajero() {
        this.pasajeroController = new PasajeroController();
        initComponents();

    }

    public void Agregar() {
        try {
            Integer id;
            id = null;
            if(LblId.getText() != null && LblId.getText() != ""){
                 id = Integer.parseInt(LblId.getText());
            }
           
            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            int dni = Integer.parseInt(txtDni.getText().trim());
            int telefono = Integer.parseInt(txtTelefono.getText().trim());
            String correo = txtCorreo.getText().trim();
            
            if(id == null){
                PasajeroDTO pasajeroDTO = new PasajeroDTO(nombre, apellido, dni, telefono, correo);
                pasajeroController.crear(pasajeroDTO);
                JOptionPane.showMessageDialog(this, "El pasajero se guardó con éxito");
            }else{
                PasajeroDTO pasajeroDTO = new PasajeroDTO(id,nombre,apellido,dni,telefono,correo);
                pasajeroController.actualizar(pasajeroDTO, id);
                JOptionPane.showMessageDialog(null, "El pasajero se actualizo correctamente");
                
            }
           
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: DNI y Teléfono deben ser números.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoPasajero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al guardar el pasajero: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LimpiarCampos() {

        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }

    public void Actualizar() {
        try {

            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            int dni = Integer.parseInt(txtDni.getText().trim());
            int telefono = Integer.parseInt(txtTelefono.getText().trim());
            String correo = txtCorreo.getText().trim();

            PasajeroDTO pasajeroDTO = new PasajeroDTO(nombre, apellido, dni, telefono, correo);
            pasajeroController.actualizarPasajero(pasajeroDTO);

            JOptionPane.showMessageDialog(this, "El pasajero se actualizó con éxito");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: DNI y Teléfono deben ser números.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el pasajero: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        LblId = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Pasajero"));
        setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblCorreo.setText("Correo electronico");
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 338, -1, -1));

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTelefono.addActionListener(formListener);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 273, 351, -1));

        lblTelefono.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTelefono.setText("Telefono");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 234, -1, -1));

        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 377, 741, -1));

        lblApellido1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblApellido1.setText("Apellido");
        add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 143, -1, -1));

        txtApellido.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtApellido.addActionListener(formListener);
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 182, 741, -1));

        lblDni1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblDni1.setText("Dni");
        add(lblDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 234, -1, -1));

        txtDni.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtDni.addActionListener(formListener);
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 273, 338, -1));

        lblNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 52, -1, -1));

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 91, 741, -1));

        BtnCancelar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setPreferredSize(new java.awt.Dimension(123, 43));
        BtnCancelar.addActionListener(formListener);
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 455, 312, 52));

        BtnGuardar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(formListener);
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 455, 312, 52));

        LblId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(LblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 39, 26, 26));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == txtTelefono) {
                NuevoPasajero.this.txtTelefonoActionPerformed(evt);
            }
            else if (evt.getSource() == txtApellido) {
                NuevoPasajero.this.txtApellidoActionPerformed(evt);
            }
            else if (evt.getSource() == txtDni) {
                NuevoPasajero.this.txtDniActionPerformed(evt);
            }
            else if (evt.getSource() == BtnCancelar) {
                NuevoPasajero.this.BtnCancelarActionPerformed(evt);
            }
            else if (evt.getSource() == BtnGuardar) {
                NuevoPasajero.this.BtnGuardarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed

        this.Agregar();
        this.LimpiarCampos();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
