/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class NuevaReserva extends javax.swing.JPanel {

    /**
     * Creates new form NuevaReserva
     */
    public NuevaReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombrePasajero = new javax.swing.JLabel();
        TxtNombrePasajero = new javax.swing.JTextField();
        BtnNuevoPasajero = new javax.swing.JButton();
        LblCantidadPersonas = new javax.swing.JLabel();
        CboxCantidadPersonas = new javax.swing.JComboBox<>();
        LblHabitacion = new javax.swing.JLabel();
        CboxHabitaciones = new javax.swing.JComboBox<>();
        LblCheckin = new javax.swing.JLabel();
        FechaCheckout = new com.toedter.calendar.JCalendar();
        FechaCheckin = new com.toedter.calendar.JCalendar();
        LblCheckout = new javax.swing.JLabel();
        LblSeña = new javax.swing.JLabel();
        TxtSeña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtFechaRegistro = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Reserva"));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNombrePasajero.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblNombrePasajero.setText("Nombre de Pasajero");
        add(LblNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 39, -1, -1));

        TxtNombrePasajero.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(TxtNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 78, 573, -1));

        BtnNuevoPasajero.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnNuevoPasajero.setText("Nuevo Pasajero");
        add(BtnNuevoPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 78, -1, -1));

        LblCantidadPersonas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblCantidadPersonas.setText("Cantidad de Personas");
        add(LblCantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 143, -1, -1));

        CboxCantidadPersonas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CboxCantidadPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 2", "Item 3", "Item 4" }));
        add(CboxCantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 182, 351, -1));

        LblHabitacion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblHabitacion.setText("Numero de Habitacion");
        add(LblHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 143, -1, -1));

        CboxHabitaciones.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CboxHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 2", "Item 3", "Item 4" }));
        add(CboxHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 182, 371, -1));

        LblCheckin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblCheckin.setText("Checkin");
        add(LblCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 247, -1, -1));
        add(FechaCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 273, 338, 195));
        add(FechaCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 273, 338, 195));

        LblCheckout.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblCheckout.setText("Checkout");
        add(LblCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 247, -1, -1));

        LblSeña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LblSeña.setText("Seña");
        add(LblSeña, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 481, -1, 26));

        TxtSeña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(TxtSeña, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 507, 310, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Fecha Registro");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 481, -1, -1));

        TxtFechaRegistro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(TxtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 507, 302, -1));

        BtnGuardar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnGuardar.setText("Guardar");
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 559, 234, 39));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevoPasajero;
    private javax.swing.JComboBox<String> CboxCantidadPersonas;
    private javax.swing.JComboBox<String> CboxHabitaciones;
    private com.toedter.calendar.JCalendar FechaCheckin;
    private com.toedter.calendar.JCalendar FechaCheckout;
    private javax.swing.JLabel LblCantidadPersonas;
    private javax.swing.JLabel LblCheckin;
    private javax.swing.JLabel LblCheckout;
    private javax.swing.JLabel LblHabitacion;
    private javax.swing.JLabel LblNombrePasajero;
    private javax.swing.JLabel LblSeña;
    private javax.swing.JTextField TxtFechaRegistro;
    private javax.swing.JTextField TxtNombrePasajero;
    private javax.swing.JTextField TxtSeña;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
