/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class NuevaHabitacion extends javax.swing.JPanel {

    /**
     * Creates new form NuevaHabitacion
     */
    public NuevaHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCamaDoble = new javax.swing.JLabel();
        CboxSimple = new javax.swing.JComboBox<>();
        lblCamaSimple = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        CboxDoble = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Habitacion"));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNumero.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        LblNumero.setText("Numero");
        add(LblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 65, -1, -1));

        txtNumero.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 104, 520, -1));

        lblCamaDoble.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblCamaDoble.setText("Camas Dobles");
        add(lblCamaDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 260, -1, -1));

        CboxSimple.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        CboxSimple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0", "1", "2", "3" }));
        CboxSimple.addActionListener(formListener);
        add(CboxSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 182, -1, -1));

        lblCamaSimple.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblCamaSimple.setText("Camas Simples");
        add(lblCamaSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 182, -1, -1));

        LblPrecio.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        LblPrecio.setText("Precio por dia");
        add(LblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 338, -1, -1));

        TxtPrecio.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 377, 520, -1));

        CboxDoble.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        CboxDoble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0", "1" }));
        add(CboxDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 260, -1, -1));

        Guardar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        Guardar.setText("Guardar");
        add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 455, 195, -1));

        Cancelar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setPreferredSize(new java.awt.Dimension(123, 43));
        add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 455, 208, -1));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == CboxSimple) {
                NuevaHabitacion.this.CboxSimpleActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void CboxSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxSimpleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> CboxDoble;
    private javax.swing.JComboBox<String> CboxSimple;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LblNumero;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JLabel lblCamaDoble;
    private javax.swing.JLabel lblCamaSimple;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
