/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controller.PasajeroController;
import com.mycompany.hotel.dto.PasajeroDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rocio
 */
public class NuevoPasajero extends javax.swing.JPanel {

    private PasajeroController pasajeroController;
   

    public NuevoPasajero(JTextField txtApellido, JTextField txtCorreo, JTextField txtDni, JTextField txtNombre, JTextField txtTelefono) {
        this.txtApellido = txtApellido;
        this.txtCorreo = txtCorreo;
        this.txtDni = txtDni;
        this.txtNombre = txtNombre;
        this.txtTelefono = txtTelefono;
    }

    public NuevoPasajero(int id, String nombre, String apellido, String dni, String telefono, String correo) {
        this();
        LblId.setText(String.valueOf(id));
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtDni.setText(dni);
        txtTelefono.setText(telefono);
        txtCorreo.setText(correo);
    }

    public NuevoPasajero() {
        this.pasajeroController = new PasajeroController();
        initComponents();
       

    }

    public void Guardar() {
        try {
            Integer id;
            id = null;
            if (LblId.getText() != null && LblId.getText() != "") {
                id = Integer.parseInt(LblId.getText());
            }

            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            int dni = Integer.parseInt(txtDni.getText().trim());
            int telefono = Integer.parseInt(txtTelefono.getText().trim());
            String correo = txtCorreo.getText().trim();

            if (id == null) {
                PasajeroDTO pasajeroDTO = new PasajeroDTO(nombre, apellido, dni, telefono, correo);
                pasajeroController.crear(pasajeroDTO);
                JOptionPane.showMessageDialog(this, "El pasajero se guardó con éxito");
            } else {
                PasajeroDTO pasajeroDTO = new PasajeroDTO(id, nombre, apellido, dni, telefono, correo);
                pasajeroController.actualizar(pasajeroDTO, id);
                JOptionPane.showMessageDialog(null, "El pasajero se actualizo correctamente");

            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: DNI y Teléfono deben ser números.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoPasajero.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al guardar el pasajero: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LimpiarCampos() {

        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        LblId = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Pasajero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setBackground(new java.awt.Color(224, 224, 224));
        lblCorreo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo electronico");
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 338, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 273, 351, -1));

        lblTelefono.setBackground(new java.awt.Color(224, 224, 224));
        lblTelefono.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 234, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 377, 741, -1));

        lblApellido1.setBackground(new java.awt.Color(224, 224, 224));
        lblApellido1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblApellido1.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido1.setText("Apellido");
        add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 143, -1, -1));

        txtApellido.setBackground(new java.awt.Color(204, 204, 204));
        txtApellido.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 182, 741, -1));

        lblDni1.setBackground(new java.awt.Color(224, 224, 224));
        lblDni1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDni1.setForeground(new java.awt.Color(255, 255, 255));
        lblDni1.setText("Dni");
        add(lblDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 234, -1, -1));

        txtDni.setBackground(new java.awt.Color(204, 204, 204));
        txtDni.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 273, 338, -1));

        lblNombre.setBackground(new java.awt.Color(224, 224, 224));
        lblNombre.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 65, -1, -1));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 104, 741, -1));

        BtnGuardar.setBackground(new java.awt.Color(51, 102, 255));
        BtnGuardar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(formListener);
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 455, 312, 52));

        LblId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(LblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 39, 26, 26));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == BtnGuardar) {
                NuevoPasajero.this.BtnGuardarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed

        this.Guardar();
        this.LimpiarCampos();
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
