/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

import com.mycompany.hotel.controller.HabitacionController;
import com.mycompany.hotel.dto.HabitacionDTO;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author mi pc
 */
public class NuevaHabitacion extends javax.swing.JPanel {

    /**
     * Creates new form NuevaHabitacion
     */
    private HabitacionController habitacionController;
    private HabitacionDTO habitacionDTO;
    
   
    
    public NuevaHabitacion(JComboBox<String> CboxDoble, JComboBox<String> CboxSimple, JLabel LblId, JTextField TxtPrecio, JTextField txtNumero) {
        this.CboxDoble = CboxDoble;
        this.CboxSimple = CboxSimple;
        this.LblId = LblId;
        this.TxtPrecio = TxtPrecio;
        this.txtNumero = txtNumero;
    }
   
    public NuevaHabitacion(int id,String numero,String camaSimple,String camaDoble,String precio){
        this.habitacionController = new HabitacionController();
        initComponents();
        this.LblId.setText(String.valueOf(id));
        this.txtNumero.setText(numero);
        this.CboxSimple.setSelectedItem(String.valueOf(camaSimple));
        this.CboxDoble.setSelectedItem(String.valueOf(camaDoble));
        this.TxtPrecio.setText(String.valueOf(precio));
    }
    
     public NuevaHabitacion() {
        this.habitacionController = new HabitacionController();
        initComponents();
    }
    
    public void Guardar() throws SQLException{
      Integer id;
        id = null;
    
        try{
            if(LblId.getText() != null && LblId.getText() != ""){
                 id = Integer.parseInt(LblId.getText());
            }
        
            String numero = txtNumero.getText().trim();
            String camaSimple = CboxSimple.getSelectedItem().toString();
            int cantSimple = Integer.parseInt(camaSimple);
            String camaDoble = CboxDoble.getSelectedItem().toString();
            int cantDoble = Integer.parseInt(camaDoble);
            String Txtprecio = TxtPrecio.getText().trim();
            BigDecimal precio = new BigDecimal(Txtprecio);
        
            if(id== null){
                HabitacionDTO habitaciondto = new HabitacionDTO(numero,cantSimple,cantDoble,precio);
                habitacionController.crear(habitaciondto);
                JOptionPane.showMessageDialog(this, "La habitacion se guardó con éxito");
            }else{
                HabitacionDTO habitaciondto = new HabitacionDTO(id,numero,cantSimple,cantDoble,precio);
                habitacionController.actualizar(habitaciondto, id);
                JOptionPane.showMessageDialog(null, "La habitacion se actualizo correctamente");
            }
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Precio por dia deben ser números.", "Error", JOptionPane.ERROR_MESSAGE);
        }catch (SQLException ex) {
            Logger.getLogger(NuevaHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void LimpiarCampos(){
        txtNumero.setText("");
        CboxSimple.setSelectedIndex(0);
        CboxDoble.setSelectedIndex(0);
        TxtPrecio.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCamaDoble = new javax.swing.JLabel();
        CboxSimple = new javax.swing.JComboBox<>();
        lblCamaSimple = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        CboxDoble = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        LblId = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Habitacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNumero.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LblNumero.setForeground(new java.awt.Color(255, 255, 255));
        LblNumero.setText("Numero");
        add(LblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 65, -1, -1));

        txtNumero.setBackground(new java.awt.Color(204, 204, 204));
        txtNumero.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 104, 520, -1));

        lblCamaDoble.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCamaDoble.setForeground(new java.awt.Color(255, 255, 255));
        lblCamaDoble.setText("Camas Dobles");
        add(lblCamaDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 260, -1, -1));

        CboxSimple.setBackground(new java.awt.Color(204, 204, 204));
        CboxSimple.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        CboxSimple.setForeground(new java.awt.Color(0, 0, 0));
        CboxSimple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0", "1", "2", "3" }));
        CboxSimple.addActionListener(formListener);
        add(CboxSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 182, -1, -1));

        lblCamaSimple.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCamaSimple.setForeground(new java.awt.Color(255, 255, 255));
        lblCamaSimple.setText("Camas Simples");
        add(lblCamaSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 182, -1, -1));

        LblPrecio.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        LblPrecio.setText("Precio por noche");
        add(LblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 338, -1, -1));

        TxtPrecio.setBackground(new java.awt.Color(204, 204, 204));
        TxtPrecio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 377, 520, -1));

        CboxDoble.setBackground(new java.awt.Color(204, 204, 204));
        CboxDoble.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        CboxDoble.setForeground(new java.awt.Color(0, 0, 0));
        CboxDoble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "0", "1" }));
        add(CboxDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 260, -1, -1));

        Guardar.setBackground(new java.awt.Color(51, 102, 255));
        Guardar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(formListener);
        add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 468, 299, 52));

        LblId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(LblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 52, 39, 26));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == CboxSimple) {
                NuevaHabitacion.this.CboxSimpleActionPerformed(evt);
            }
            else if (evt.getSource() == Guardar) {
                NuevaHabitacion.this.GuardarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void CboxSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxSimpleActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        try {
            this.Guardar();
            this.LimpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxDoble;
    private javax.swing.JComboBox<String> CboxSimple;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblNumero;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JLabel lblCamaDoble;
    private javax.swing.JLabel lblCamaSimple;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
