/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class NuevoPasajero extends javax.swing.JPanel {

    /**
     * Creates new form NuevoPasajero
     */
    public NuevoPasajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Pasajero"));
        setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblCorreo.setText("Correo electronico");
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 338, -1, -1));

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTelefono.addActionListener(formListener);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 273, 351, -1));

        lblTelefono.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTelefono.setText("Telefono");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 234, -1, -1));

        txtCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 377, 741, -1));

        lblApellido1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblApellido1.setText("Apellido");
        add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 143, -1, -1));

        txtApellido.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtApellido.addActionListener(formListener);
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 182, 741, -1));

        lblDni1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblDni1.setText("Dni");
        add(lblDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 234, -1, -1));

        txtDni.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtDni.addActionListener(formListener);
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 273, 338, -1));

        lblNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 52, -1, -1));

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 91, 741, -1));

        BtnCancelar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setPreferredSize(new java.awt.Dimension(123, 43));
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 455, 312, 52));

        BtnGuardar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BtnGuardar.setText("Guardar");
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 455, 312, 52));
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == txtTelefono) {
                NuevoPasajero.this.txtTelefonoActionPerformed(evt);
            }
            else if (evt.getSource() == txtApellido) {
                NuevoPasajero.this.txtApellidoActionPerformed(evt);
            }
            else if (evt.getSource() == txtDni) {
                NuevoPasajero.this.txtDniActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
