/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotel.view;

/**
 *
 * @author mi pc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        LblTituloApp = new javax.swing.JLabel();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuOpReservas = new javax.swing.JMenu();
        OpListaReserva = new javax.swing.JMenuItem();
        OpRealizarReserva = new javax.swing.JMenuItem();
        jMenuOpHabitacion = new javax.swing.JMenu();
        OpListaHabitacion = new javax.swing.JMenuItem();
        OpCargarHabitacion = new javax.swing.JMenuItem();
        jMenuOpPasajero = new javax.swing.JMenu();
        OpListaPasajero = new javax.swing.JMenuItem();
        OpCargarPasajero = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel \"Titos\"");
        setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTituloApp.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        LblTituloApp.setText("Gestion Hotelera");
        jPanelPrincipal.add(LblTituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 247, -1, 78));

        jMenuOpReservas.setText("Reserva");

        OpListaReserva.setText("Lista Reservas");
        OpListaReserva.addActionListener(formListener);
        jMenuOpReservas.add(OpListaReserva);

        OpRealizarReserva.setText("Realizar Reserva");
        OpRealizarReserva.addActionListener(formListener);
        jMenuOpReservas.add(OpRealizarReserva);

        jMenuPrincipal.add(jMenuOpReservas);

        jMenuOpHabitacion.setText("Habitacion");

        OpListaHabitacion.setText("Lista Habitaciones");
        OpListaHabitacion.addActionListener(formListener);
        jMenuOpHabitacion.add(OpListaHabitacion);

        OpCargarHabitacion.setText("Cargar Habitacion");
        OpCargarHabitacion.addActionListener(formListener);
        jMenuOpHabitacion.add(OpCargarHabitacion);

        jMenuPrincipal.add(jMenuOpHabitacion);

        jMenuOpPasajero.setText("Pasajero");

        OpListaPasajero.setText("Lista Pasajeros");
        OpListaPasajero.addActionListener(formListener);
        jMenuOpPasajero.add(OpListaPasajero);

        OpCargarPasajero.setText("Cargar Pasajero");
        OpCargarPasajero.addActionListener(formListener);
        jMenuOpPasajero.add(OpCargarPasajero);

        jMenuPrincipal.add(jMenuOpPasajero);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == OpListaReserva) {
                Principal.this.OpListaReservaActionPerformed(evt);
            }
            else if (evt.getSource() == OpRealizarReserva) {
                Principal.this.OpRealizarReservaActionPerformed(evt);
            }
            else if (evt.getSource() == OpListaHabitacion) {
                Principal.this.OpListaHabitacionActionPerformed(evt);
            }
            else if (evt.getSource() == OpCargarHabitacion) {
                Principal.this.OpCargarHabitacionActionPerformed(evt);
            }
            else if (evt.getSource() == OpListaPasajero) {
                Principal.this.OpListaPasajeroActionPerformed(evt);
            }
            else if (evt.getSource() == OpCargarPasajero) {
                Principal.this.OpCargarPasajeroActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void OpCargarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCargarPasajeroActionPerformed
       this.setContentPane(new NuevoPasajero());
       pack();
    }//GEN-LAST:event_OpCargarPasajeroActionPerformed

    private void OpListaPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpListaPasajeroActionPerformed
      this.setContentPane(new ListaPasajeros());
      pack();
    }//GEN-LAST:event_OpListaPasajeroActionPerformed

    private void OpCargarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCargarHabitacionActionPerformed
        this.setContentPane(new NuevaHabitacion());
        pack();
    }//GEN-LAST:event_OpCargarHabitacionActionPerformed

    private void OpListaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpListaHabitacionActionPerformed
        this.setContentPane(new ListaHabitaciones());
        pack();
    }//GEN-LAST:event_OpListaHabitacionActionPerformed

    private void OpRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpRealizarReservaActionPerformed
      this.setContentPane(new NuevaReserva());
      pack();
    }//GEN-LAST:event_OpRealizarReservaActionPerformed

    private void OpListaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpListaReservaActionPerformed
        this.setContentPane(new ListaReservas());
        pack();
    }//GEN-LAST:event_OpListaReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTituloApp;
    private javax.swing.JMenuItem OpCargarHabitacion;
    private javax.swing.JMenuItem OpCargarPasajero;
    private javax.swing.JMenuItem OpListaHabitacion;
    private javax.swing.JMenuItem OpListaPasajero;
    private javax.swing.JMenuItem OpListaReserva;
    private javax.swing.JMenuItem OpRealizarReserva;
    private javax.swing.JMenu jMenuOpHabitacion;
    private javax.swing.JMenu jMenuOpPasajero;
    private javax.swing.JMenu jMenuOpReservas;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
   

}
